### ISSUE TITLE
Cart quantity 0 or remove from cart button

### ISSUE THREAD

**Issue by Afplaktape** [wagnerwagner/merx-starterkit#11]
Hi there, It's not possible to set the quantity in the cart to 0 (happening with the Starterkit and also in the demo you provided: https://starterkit.merx.wagnerwagner.de/). Is there a way to remove products from the cart once they're there?

**Comment by tobiasfabian** [comment]
Thank you for creating an issue.

It’s fixed with [Merx 1.7.2](https://github.com/wagnerwagner/merx/releases/tag/v1.7.2).

### Technical explanation

There is an issue with [`Kirby\Toolkit\Collection::__unset()`](https://github.com/getkirby/kirby/blob/ee2669e6dd091399fd7981381e1bd8cbd94d90a6/src/Toolkit/Collection.php#L124). 

The [`Cart`](https://github.com/wagnerwagner/merx/blob/main/src/Cart.php) (a child component of `Collection`) stores cart items with lowercase keys (e.g. `lorem`, see [ProductList.php#L159](https://github.com/wagnerwagner/merx/blob/main/src/ProductList.php#L159)). The [updateItem method](https://github.com/wagnerwagner/merx/blob/82db3b0473ac907405efc2aa5267a4e909940b01/src/ProductList.php#L56) uses mixed-case keys (e.g. `LoREm`). To update an item the method calls `Kirby\Toolkit\Collection::__set()`, to remove an item the method calls `Kirby\Toolkit\Collection::__unset()`.

[`Kirby\Toolkit\Collection::__set()`](https://github.com/getkirby/kirby/blob/ee2669e6dd091399fd7981381e1bd8cbd94d90a6/src/Toolkit/Collection.php#L100) transforms mixed-case to lowercase, [`Kirby\Toolkit\Collection::__unset()`](https://github.com/getkirby/kirby/blob/ee2669e6dd091399fd7981381e1bd8cbd94d90a6/src/Toolkit/Collection.php#L124) does not.
