### ISSUE TITLE
Paypal-Issue status 201 - redirect to link

### ISSUE THREAD

**Issue by 3ron2** [wagnerwagner/merx-starterkit#6]
Dear Developers,

after checkout, i will be redirected to "example.com/api/shop/checkout".
There i get a code line included a link, which redirected to the Paypal-Site, then the Checkout can be done fine.

` {"status":201,"redirect":"https:\/\/www.paypal.com\/checkoutnow?token=........"}`

Whats the mistake, that i won't redirected directly to Paypal, ich can't find it. :(

Best Regards

Luca

**Comment by tobiasfabian** [comment]
This issue is most likely related to a JavaScript error. If you haven't added Stripe keys, the checkout JavaScript won't work properly. I have improved/fixed the behaviour of the checkout when no PayPal/Stripe keys are provided ([`feature/improved-onboarding`](https://github.com/wagnerwagner/merx-starterkit/tree/feature/improved-onboarding)).

As soon as there is a fix for #7, I will merge the branch into main.

**Comment by tobiasfabian** [comment]
See [v1.1.0](https://github.com/wagnerwagner/merx-starterkit/releases/tag/v1.1.0)
