### ISSUE TITLE
Deprecation error in PaypalSDK

### ISSUE THREAD

**Issue by jamiehunterdesign** [wagnerwagner/merx-starterkit#9]
I am getting this error when setting up the starterkit:

`{"status":"error","message":"The payment could not be initialized.","code":500,"exception":"Kirby\\Exception\\Exception","key":"error.merx.initializePayment","file":"\/merx-starterkit\/site\/plugins\/merx\/src\/Merx.php","line":257,"details":{"message":"Creation of dynamic property PayPalCheckoutSdk\\Core\\PayPalHttpClient::$curlCls is deprecated","code":8192,"file":"\/Users\/jamiehunter\/Documents\/htdocs\/merx-starterkit\/site\/plugins\/merx\/vendor\/paypal\/paypalhttp\/lib\/PayPalHttp\/HttpClient.php","line":38},"route":"shop\/checkout"}`

PayPalCheckoutSdk has been deprecated (https://github.com/paypal/Checkout-PHP-SDK), the Paypal integration needs updating to the REST API.

**Comment by tobiasfabian** [comment]
Thanks for your issue @jamiehunterdesign.

I never got this deprecation warning before, but I was able to reproduce it.

This message appears since PHP 8.2, which marks [dynamic properties as deprecated](https://wiki.php.net/rfc/deprecate_dynamic_properties).

In a future version of Merx, I will replace the PayPal PHP SDK. For now, you can safely suppress deprecation warnings with the following code.
```php
error_reporting(E_ALL ^ E_DEPRECATED);
```
You can add it at the top of your `config.php` or add it to your `index.php`.

**Comment by tobiasfabian** [comment]
We removed the PayPal SDK in Merx [1.8.0-beta.1](https://github.com/wagnerwagner/merx/releases/tag/v1.8.0-beta.1). The current version of the Starterkit ([1.3.0](https://github.com/wagnerwagner/merx-starterkit/releases/tag/v1.3.0)) uses this Merx beta version.
